#pragma once

/*
	Define animations in relation to accociated spritesheets (with defined frames)
*/

//Main character spritesheet animation indexes
enum class CharacterSS00Animations : unsigned
{
	//Gunner
	GUNNER_00_ATTACK_LEFT,
	GUNNER_00_ATTACK_RIGHT,
	GUNNER_00_IDLE_LEFT,
	GUNNER_00_IDLE_RIGHT,
	GUNNER_00_WALK_LEFT,
	GUNNER_00_WALK_RIGHT,

	//Knight
	KNIGHT_00_ATTACK_LEFT,
	KNIGHT_00_ATTACK_RIGHT,
	KNIGHT_00_IDLE_LEFT,
	KNIGHT_00_IDLE_RIGHT,
	KNIGHT_00_WALK_LEFT,
	KNIGHT_00_WALK_RIGHT,

	//Mage
	MAGE_00_ATTACK_LEFT,
	MAGE_00_ATTACK_RIGHT,
	MAGE_00_IDLE_LEFT,
	MAGE_00_IDLE_RIGHT,
	MAGE_00_POWERUP_LEFT,
	MAGE_00_POWERUP_RIGHT,
	MAGE_00_WALK_LEFT,
	MAGE_00_WALK_RIGHT,

	COUNT
};

//Main enemy spritesheet animation indexes
enum class EnemySS00Animations : unsigned 
{
	//Robot_00
	ROBOT_00_ATTACK_LEFT,
	ROBOT_00_ATTACK_RIGHT,
	ROBOT_00_IDLE_LEFT,
	ROBOT_00_IDLE_RIGHT,
	ROBOT_00_WALK_LEFT,
	ROBOT_00_WALK_RIGHT,

	//Skeleton Archer
	SKELETON_ARCHER_00_ATTACK_LEFT,
	SKELETON_ARCHER_00_ATTACK_RIGHT,
	SKELETON_ARCHER_00_IDLE_LEFT,
	SKELETON_ARCHER_00_IDLE_RIGHT,
	SKELETON_ARCHER_00_WALK_LEFT,
	SKELETON_ARCHER_00_WALK_RIGHT,

	//Skeleton Part 1
	SKELETON_00_ATTACK_LEFT,
	SKELETON_00_ATTACK_RIGHT,

	//Skeleton Chief
	SKELETON_CHIEF_00_ATTACK_LEFT,
	SKELETON_CHIEF_00_ATTACK_RIGHT,
	SKELETON_CHIEF_00_IDLE_LEFT,
	SKELETON_CHIEF_00_IDLE_RIGHT,
	SKELETON_CHIEF_00_WALK_LEFT,
	SKELETON_CHIEF_00_WALK_RIGHT,

	//Skeleton Part 2
	SKELETON_00_IDLE_LEFT,
	SKELETON_00_IDLE_RIGHT,
	SKELETON_00_WALK_LEFT,
	SKELETON_00_WALK_RIGHT,

	//Wolf
	WOLF_00_ATTACK_LEFT,
	WOLF_00_ATTACK_RIGHT,
	WOLF_00_IDLE_LEFT,
	WOLF_00_IDLE_RIGHT,
	WOLF_00_WALK_LEFT,
	WOLF_00_WALK_RIGHT,

	COUNT
};

enum class EffectsSS00Animations : unsigned
{
	BLOODSPLATTER_00,
	BLOODSPLATTER_01,
	BOOST_00,
	CRYSTAL_BALL_LOOP_00,
	CRYSTAL_BALL_LOOP_01,
	ENERGY_00,
	ENERGY_01,
	ENERGY_02,
	EXPLOSION_00,
	EXPLOSION_01,
	EXPLOSION_02,
	EXPLOSION_03,
	EXPLOSION_04,
	EXPLOSION_05,
	EXPLOSION_06,
	EXPLOSION_07,
	SUPER_EFFECT_00,
	COUNT
};

enum class WeaponsSS01Animations : unsigned
{
	ANGEL_IDLE_00,
	ANGEL_SPAWN_00,
	GATE_IDLE_00,
	GATE_SPAWN_00,
	LIGHT_BULLET_00,
	HOLY_BEAM_VERTICAL_00,
	WATER_DRAGON_ACTIVE_00,
	WATER_DRAGON_DESPAWN_00,
	WATER_DRAGON_SPAWN_00,
	COUNT
};